class SampleData {
  static const String libraryData = '''
  [
    {
      "id": "1",
      "name": "Mathematics",
      "type": "FOLDER",
      "parent_id": null,
      "user_id": "user_123",
      "path": "/Mathematics/",
      "created_at": "2024-04-22T10:00:00Z",
      "updated_at": "2024-05-17T15:30:00Z",
      "metadata": null,
      "is_deleted": false,
      "sort_order": 1
    },
    {
      "id": "2",
      "name": "Physics",
      "type": "FOLDER",
      "parent_id": null,
      "user_id": "user_123",
      "path": "/Physics/",
      "created_at": "2024-04-27T09:15:00Z",
      "updated_at": "2024-05-19T11:45:00Z",
      "metadata": null,
      "is_deleted": false,
      "sort_order": 2
    },
    {
      "id": "3",
      "name": "Computer Science",
      "type": "FOLDER",
      "parent_id": null,
      "user_id": "user_123",
      "path": "/Computer Science/",
      "created_at": "2024-05-02T14:20:00Z",
      "updated_at": "2024-05-21T16:30:00Z",
      "metadata": null,
      "is_deleted": false,
      "sort_order": 3
    },
    {
      "id": "4",
      "name": "Calculus",
      "type": "FOLDER",
      "parent_id": "1",
      "user_id": "user_123",
      "path": "/Mathematics/Calculus/",
      "created_at": "2024-04-24T11:30:00Z",
      "updated_at": "2024-05-18T14:20:00Z",
      "metadata": null,
      "is_deleted": false,
      "sort_order": 1
    },
    {
      "id": "5",
      "name": "Algebra",
      "type": "FOLDER",
      "parent_id": "1",
      "user_id": "user_123",
      "path": "/Mathematics/Algebra/",
      "created_at": "2024-04-26T13:45:00Z",
      "updated_at": "2024-05-20T10:15:00Z",
      "metadata": null,
      "is_deleted": false,
      "sort_order": 2
    },
    {
      "id": "6",
      "name": "Derivatives Notes",
      "type": "NOTE",
      "parent_id": "4",
      "user_id": "user_123",
      "path": "/Mathematics/Calculus/Derivatives Notes",
      "created_at": "2024-05-07T09:00:00Z",
      "updated_at": "2024-05-21T12:30:00Z",
      "metadata": {"word_count": 1250, "tags": ["calculus", "derivatives"]},
      "is_deleted": false,
      "sort_order": 1
    },
    {
      "id": "7",
      "name": "Integration Techniques",
      "type": "DOCUMENT",
      "parent_id": "4",
      "user_id": "user_123",
      "path": "/Mathematics/Calculus/Integration Techniques",
      "created_at": "2024-05-10T16:45:00Z",
      "updated_at": "2024-05-20T14:20:00Z",
      "metadata": {"file_type": "pdf", "pages": 25},
      "is_deleted": false,
      "sort_order": 2
    },
    {
      "id": "8",
      "name": "Calculus Lecture 1",
      "type": "MEDIA",
      "parent_id": "4",
      "user_id": "user_123",
      "path": "/Mathematics/Calculus/Calculus Lecture 1",
      "created_at": "2024-05-12T08:30:00Z",
      "updated_at": "2024-05-21T11:45:00Z",
      "metadata": {"duration_minutes": 45, "transcribed": true},
      "is_deleted": false,
      "sort_order": 3
    },
    {
      "id": "9",
      "name": "Linear Equations Flashcards",
      "type": "FLASHCARD",
      "parent_id": "5",
      "user_id": "user_123",
      "path": "/Mathematics/Algebra/Linear Equations Flashcards",
      "created_at": "2024-05-14T10:15:00Z",
      "updated_at": "2024-05-22T06:30:00Z",
      "metadata": {"card_count": 35, "mastered": 22},
      "is_deleted": false,
      "sort_order": 1
    },
    {
      "id": "10",
      "name": "Quantum Mechanics",
      "type": "FOLDER",
      "parent_id": "2",
      "user_id": "user_123",
      "path": "/Physics/Quantum Mechanics/",
      "created_at": "2024-04-30T15:20:00Z",
      "updated_at": "2024-05-19T13:10:00Z",
      "metadata": null,
      "is_deleted": false,
      "sort_order": 1
    },
    {
      "id": "11",
      "name": "Classical Mechanics Notes",
      "type": "NOTE",
      "parent_id": "2",
      "user_id": "user_123",
      "path": "/Physics/Classical Mechanics Notes",
      "created_at": "2024-05-04T12:00:00Z",
      "updated_at": "2024-05-20T15:45:00Z",
      "metadata": {"word_count": 890, "tags": ["mechanics", "newton"]},
      "is_deleted": false,
      "sort_order": 2
    },
    {
      "id": "12",
      "name": "Wave Function Analysis",
      "type": "DOCUMENT",
      "parent_id": "10",
      "user_id": "user_123",
      "path": "/Physics/Quantum Mechanics/Wave Function Analysis",
      "created_at": "2024-05-08T14:30:00Z",
      "updated_at": "2024-05-21T09:20:00Z",
      "metadata": {"file_type": "pdf", "pages": 12},
      "is_deleted": false,
      "sort_order": 1
    },
    {
      "id": "13",
      "name": "Data Structures",
      "type": "FOLDER",
      "parent_id": "3",
      "user_id": "user_123",
      "path": "/Computer Science/Data Structures/",
      "created_at": "2024-05-04T11:10:00Z",
      "updated_at": "2024-05-21T17:25:00Z",
      "metadata": null,
      "is_deleted": false,
      "sort_order": 1
    },
    {
      "id": "14",
      "name": "Algorithms",
      "type": "FOLDER",
      "parent_id": "3",
      "user_id": "user_123",
      "path": "/Computer Science/Algorithms/",
      "created_at": "2024-05-06T13:45:00Z",
      "updated_at": "2024-05-22T05:30:00Z",
      "metadata": null,
      "is_deleted": false,
      "sort_order": 2
    },
    {
      "id": "15",
      "name": "Binary Trees Explained",
      "type": "NOTE",
      "parent_id": "13",
      "user_id": "user_123",
      "path": "/Computer Science/Data Structures/Binary Trees Explained",
      "created_at": "2024-05-11T16:20:00Z",
      "updated_at": "2024-05-22T14:45:00Z",
      "metadata": {"word_count": 1580, "tags": ["trees", "data-structures"]},
      "is_deleted": false,
      "sort_order": 1
    },
    {
      "id": "16",
      "name": "Sorting Algorithms",
      "type": "DOCUMENT",
      "parent_id": "14",
      "user_id": "user_123",
      "path": "/Computer Science/Algorithms/Sorting Algorithms",
      "created_at": "2024-05-13T09:40:00Z",
      "updated_at": "2024-05-22T18:15:00Z",
      "metadata": {"file_type": "pdf", "pages": 18},
      "is_deleted": false,
      "sort_order": 1
    },
    {
      "id": "17",
      "name": "Algorithm Complexity Flashcards",
      "type": "FLASHCARD",
      "parent_id": "14",
      "user_id": "user_123",
      "path": "/Computer Science/Algorithms/Algorithm Complexity Flashcards",
      "created_at": "2024-05-15T11:25:00Z",
      "updated_at": "2024-05-22T20:30:00Z",
      "metadata": {"card_count": 28, "mastered": 15},
      "is_deleted": false,
      "sort_order": 2
    },
    {
      "id": "18",
      "name": "Quick Study Notes",
      "type": "NOTE",
      "parent_id": null,
      "user_id": "user_123",
      "path": "/Quick Study Notes",
      "created_at": "2024-05-17T14:15:00Z",
      "updated_at": "2024-05-22T21:45:00Z",
      "metadata": {"word_count": 320, "tags": ["quick", "misc"]},
      "is_deleted": false,
      "sort_order": 4
    },
    {
      "id": "19",
      "name": "Research Papers",
      "type": "FOLDER",
      "parent_id": null,
      "user_id": "user_123",
      "path": "/Research Papers/",
      "created_at": "2024-05-10T10:30:00Z",
      "updated_at": "2024-05-19T12:20:00Z",
      "metadata": null,
      "is_deleted": false,
      "sort_order": 5
    },
    {
      "id": "20",
      "name": "AI in Education Paper",
      "type": "DOCUMENT",
      "parent_id": "19",
      "user_id": "user_123",
      "path": "/Research Papers/AI in Education Paper",
      "created_at": "2024-05-16T13:50:00Z",
      "updated_at": "2024-05-21T16:10:00Z",
      "metadata": {"file_type": "pdf", "pages": 45, "authors": ["Dr. Smith", "Prof. Johnson"]},
      "is_deleted": false,
      "sort_order": 1
    }
  ]
  ''';
}
