// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGzosi1uDlgLCduCVmyMeu-0dJTu2sz2k',
    appId: '1:337887949979:web:5e3ae85bb2aae2e012423e',
    messagingSenderId: '337887949979',
    projectId: 'studymind-ai',
    authDomain: 'studymind-ai.firebaseapp.com',
    storageBucket: 'studymind-ai.firebasestorage.app',
    measurementId: 'G-R5WNYK0YRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDleLFO8RzsAd6-y_Lw1OM7S_XiwHWk9GQ',
    appId: '1:337887949979:android:9ae41e43c52d763412423e',
    messagingSenderId: '337887949979',
    projectId: 'studymind-ai',
    storageBucket: 'studymind-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD3SuwbxhgL2pWPLv8gn8CROx48UWUYng',
    appId: '1:337887949979:ios:31f7aa25fca904f812423e',
    messagingSenderId: '337887949979',
    projectId: 'studymind-ai',
    storageBucket: 'studymind-ai.firebasestorage.app',
    iosBundleId: 'com.example.studymind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD3SuwbxhgL2pWPLv8gn8CROx48UWUYng',
    appId: '1:337887949979:ios:31f7aa25fca904f812423e',
    messagingSenderId: '337887949979',
    projectId: 'studymind-ai',
    storageBucket: 'studymind-ai.firebasestorage.app',
    iosBundleId: 'com.example.studymind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGzosi1uDlgLCduCVmyMeu-0dJTu2sz2k',
    appId: '1:337887949979:web:769a2fee0252714112423e',
    messagingSenderId: '337887949979',
    projectId: 'studymind-ai',
    authDomain: 'studymind-ai.firebaseapp.com',
    storageBucket: 'studymind-ai.firebasestorage.app',
    measurementId: 'G-YWLSEGRRDR',
  );
}
